name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.1
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: ">=2.15.0-262.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^4.0.2
  http: ^1.0.0
  html: ^0.15.4
  url_launcher: ^6.1.11
  collection: ^1.17.1

